### ISSUE TITLE
no export in contao backend

### ISSUE THREAD

**Issue by arminfrey** [heimrichhannot/contao-exporter-bundle#12]
Hallo,

ich habe in /contao/dca/jungbuettel.php folgenden Eintrag für den Exporter:
    
 ```
$GLOBALS['TL_DCA']['tl_jungbuettel']['list']['global_operations']['export_csv'] = 
    \Contao\System::getContainer()->get('huh.exporter.action.backendexport')
        ->getGlobalOperation('export_csv',$GLOBALS['TL_LANG']['MSC']['export_csv'])
;
```
 (Das ist ein eigenes Modul, das die Pflege von Jugendlichen mit ihrem Erziehungsberechtigten erlaubt).    Der Exportbutton oder -link wird auch angezeigt in der Liste.
    
In /contao/config/config.php habe ich folgenden Eintrag:
    
```
$GLOBALS['BE_MOD']['jungbuettel_module']['jungbuettel_collection']['jbexpcsv'] = [
        'export_csv' => ['huh.exporter.action.backendexport', 'export']
        ]; 
```
 (bisschen blöd benannt, jungbuettel_collection ist das Modul).

Das "jbexpcsv" wird mir in der Exporterkonfiguration auch als Globale Operation vorgeschlagen und die richtige Tabelle wird mir auch vorgeschlagen.

Für mich sieht das soweit passend aus nach der Anleitung in der README.md

Nur bekomme ich keinen Download. Wenn ich auf den Link klicke, flackert kurz die Seite und das war es. Keine Fehlermeldungen, beim Debug auch nichts feststellbar, denn es passiert einfach nichts.

Cache ist geleert. Contao 4.13.6,, contao-exporter-bundle 0.11.1

Grüße Armin

![exporter1](https://user-images.githubusercontent.com/104427130/179954851-03bb2da5-f37d-4048-9e1a-a4ad7d873dcf.png)
![exporter2](https://user-images.githubusercontent.com/104427130/179954858-4e2f9d0b-e127-4b5a-b48d-c853494818df.png)

**Comment by koertho** [comment]
Das 'jbexpcsv' in `$GLOBALS['BE_MOD']['jungbuettel_module']['jungbuettel_collection']['jbexpcsv']` dürfte eines zu viel sein. Anschließend als globale Operation `export_csv` auswählen, dann müsste es passen.

**Comment by koertho** [comment]
Du must im backend module noch die Table ergänzen, also 
```
$GLOBALS['BE_MOD']['jungbuettel_module']['jungbuettel_collection']['jbexpcsv'] = [
        'export_csv' => ['huh.exporter.action.backendexport', 'export'],
        'tables' => ['tl_jungbuettel'],
        ]; 
```

**Comment by arminfrey** [comment]
Mit
```
$GLOBALS['BE_MOD']['jungbuettel_module']['jungbuettel_collection'] = [
        'export_csv' => ['huh.exporter.action.backendexport', 'export'],
        'tables' => ['tl_jungbuettel'],
]; 
```

(ohne jbexpcsv!) funktioniert! 

Danke.

**Comment by koertho** [comment]
Sehr schön. Ich werde das mal in der Readme ergänzen.
