### ISSUE TITLE
Exporter class for exporter configuration 2 not found

### ISSUE THREAD

**Issue by Misco** [heimrichhannot/contao-exporter-bundle#2]
when click export error shows up: Exporter class for exporter configuration 2 not found

in the configuration i can select only one Exportclass: ExelExporter_05d3ef3
witch path should this file be?
i use this extension in my own extension in src (not vendor) 
its a contao 4.6.14

thank you for this great extension

**Comment by koertho** [comment]
Sorry, what do you mean with "i use this extension in my own extension in src (not vendor)"? You must install this bundle with composer. Then you need to do the steps written in the readme.

**Comment by Misco** [comment]
sorry to confuse you.
your extension is installed in vendor via contao manager.
my extension is in src.
I try to find out why the Exportclass can not be found.
my idea was its because of changes in Contao 4.6 or because my extension is in src,

thank you

**Comment by Misco** [comment]
I removed the custom error to get more informations:
HeimrichHannot\ContaoExporterBundle\Action\ExportAction::export() must be an instance of HeimrichHannot\ContaoExporterBundle\Model\ExporterModel, null given, called in /www/htdocs/w01192bf/project/vendor/heimrichhannot/contao-exporter-bundle/src/Action/BackendExportAction.php on line 76

Any suggestion? Thanks

**Comment by koertho** [comment]
@Misco I found a bug related to changes in class caching in symfony 4. I fixed it in version 0.7. Hope this will also fix your problem. Please report back!

**Comment by Misco** [comment]
@koertho there is an error while updating:

Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 2 installs, 16 updates, 0 removals
  - Updating clue/stream-filter (v1.4.0 => v1.4.1): Downloading (100%)
  - Removing doctrine/persistence (1.1.x-dev 3da7c9d)
  - Installing doctrine/persistence (1.2.x-dev 43526ae): Downloading (100%)
  - Installing soundasleep/html2text (1.1.0): Downloading (100%)
  - Removing symfony/dom-crawler (3.4.x-dev d40023c)
  - Installing symfony/dom-crawler (4.2.x-dev 53c9776): Loading from cache
  - Removing wa72/htmlpagedom (1.3.x-dev 1e6685c)
  - Installing wa72/htmlpagedom (1.x-dev c28af5f): Downloading (100%)
  - Removing scheb/two-factor-bundle (v3.17.2)
  - Installing scheb/two-factor-bundle (3.x-dev fa5de3b): Downloading (100%)
  - Downgrading league/uri-parser (dev-master 6715484 => 1.4.1): Loading from cache
  - Downgrading league/uri-interfaces (dev-master 081760c => 1.1.1): Loading from cache
  - Downgrading league/uri-schemes (dev-master f821a44 => 1.2.1): Loading from cache
  - Updating knplabs/knp-time-bundle (1.8.0 => v1.9.1): Downloading (100%)
  - Removing doctrine/dbal (dev-master 546cd67)
  - Installing doctrine/dbal (dev-master e4978c2): Downloading (100%)
  - Installing hackzilla/password-generator (1.4.1): Downloading (100%)
  - Updating heimrichhannot/contao-utils-bundle (2.86.0 => 2.95.0): Downloading (100%)
  - Updating heimrichhannot/contao-field-value-copier-bundle (1.0.3 => 1.1.0): Downloading (100%)
  - Removing heimrichhannot/contao-exporter-bundle (dev-master 2dfdab1)
  - Installing heimrichhannot/contao-exporter-bundle (dev-master e0deeca): Downloading (100%)
  - Removing sonata-project/google-authenticator (2.x-dev 7e22988)
  - Installing sonata-project/google-authenticator (2.x-dev b68241d): Downloading (100%)
  - Removing symfony/security (4.2.x-dev 9895679)
  - Installing symfony/security (4.2.x-dev a92e288): Downloading (100%)
  - Removing twig/twig (2.x-dev d997512)
  - Installing twig/twig (2.x-dev cf733f4): Downloading (100%)
Package heimrichhannot/contao-fieldpalette is abandoned, you should avoid using it. Use heimrichhannot/contao-fieldpalette-bundle instead.
Generating optimized autoload files
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication

In DefinitionErrorExceptionPass.php line 54:
                                                                               
  Cannot autowire service "huh.utils.container": argument "$scopeMatcher" of   
  method "HeimrichHannot\UtilsBundle\Container\ContainerUtil::__construct()"   
  references class "Contao\CoreBundle\Routing\ScopeMatcher" but no such servi  
  ce exists. You should maybe alias this class to the existing "contao.routin  
  g.scope_matcher" service.                                                    
                                                                               

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception

In ScriptHandler.php line 87:
                                                                               
  An error occurred while executing the "contao:install-web-dir" command:      
  In DefinitionErrorExceptionPass.php line 54:                                 
                                                                               
                                                                               
    Cannot autowire service "huh.utils.container": argument "$scopeMatcher" o  
  f                                                                            
    method "HeimrichHannot\UtilsBundle\Container\ContainerUtil::__construct()  
  "                                                                            
    references class "Contao\CoreBundle\Routing\ScopeMatcher" but no such ser  
  vi                                                                           
    ce exists. You should maybe alias this class to the existing "contao.rout  
  in                                                                           
    g.scope_matcher" service.                                                  
                                                                               

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...


# Process terminated with exit code 1
# Result: General error


---

### The background task has stopped unexpectedly ###

Thanks for your effort

**Comment by koertho** [comment]
@Misco That is an problem with the service container configuration of Contao 4.6. 4.7 does fix this problem.

**Comment by Misco** [comment]
ah ok, thank you i will try

**Comment by Misco** [comment]
It´s working now. Thanks
